### ISSUE TITLE
nodemon crashing on MAC

### ISSUE THREAD

**Issue by wayneseymour** [jrcryer/generator-mean#11]
I just typed `grunt` after scaffolding and received:

``` sh
Running "jshint:all" (jshint) task
>> 8 files lint free.

Running "compass:dist" (compass) task
unchanged app/styles/app.scss
Compilation took 0.08s

Running "compass:server" (compass) task
unchanged app/styles/app.scss
Compilation took 0.079s

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Running "nodemon:dev" (nodemon) task
Waiting...[nodemon] v1.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express app started on port 3000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/wayne/dev/lrn/mean-lrn/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/Users/wayne/dev/lrn/mean-lrn/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/Users/wayne/dev/lrn/mean-lrn/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by carlosperalta88** [comment]
happened the same to me. Waiting for some fixes or directions here.

**Comment by jrcryer** [comment]
Sorry for not picking this up sooner guys - I'm taking a look at it now!

**Comment by jrcryer** [comment]
Fix released:

https://www.npmjs.org/package/generator-mean

**Comment by sospedra** [comment]
Exactly the same. Just today.

**Comment by jrcryer** [comment]
Hi @edravis - do you know which version of Node you are using?

**Comment by sospedra** [comment]
@jrcryer  v0.10.30
