### ISSUE TITLE
When I run grunt I get some errors

### ISSUE THREAD

**Issue by siddhion** [jrcryer/generator-mean#15]
Installation went fine but upon running `grunt` I ran into some errors. Is this a bug?

```
$ grunt
Running "jshint:all" (jshint) task
>> 8 files lint free.

Running "compass:dist" (compass) task
   create public/styles/app.css (4.247s)
Compilation took 4.248s

Running "compass:server" (compass) task
unchanged app/styles/app.scss
Compilation took 0.218s

Running "concurrent:tasks" (concurrent) task
Running "nodemon:dev" (nodemon) task
Running "watch" task
Waiting...
[nodemon] v1.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express app started on port 3000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/max/dev/jrcryer-MEAN/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/max/dev/jrcryer-MEAN/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/max/dev/jrcryer-MEAN/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jrcryer** [comment]
Thanks for raising this,  I think this is a dup of #11, it was fixed yesterday and I need to release the fix later today.

Hope this helps :+1:

**Comment by jrcryer** [comment]
Fix released:

https://www.npmjs.org/package/generator-mean
