### ISSUE TITLE
Express middleware error on grunt

### ISSUE THREAD

**Issue by jonopus** [jrcryer/generator-mean#17]
I'm getting this error on grunt

Error: Most middleware (like session) is no longer bundled with Express and must be installed separately. Please
see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (C:\meanproject\node_modules\express\lib\express.js:89:
3)
    at module.exports (C:\meanproject\node_modules\connect-mongo\lib\connect-mongo.js:30:22)
    at Object.<anonymous> (C:\meanproject\config\express.js:6:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\meanproject\server.js:41:1)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jrcryer** [comment]
Thanks @jonopus - I'll take a look at this for you.

**Comment by adambarthelson** [comment]
same issue

**Comment by jrcryer** [comment]
Thanks for raising this - I've released a fix which now means this generator works with Express 4.

**Comment by adambarthelson** [comment]
:+1:
