### ISSUE TITLE
grunt command fails

### ISSUE THREAD

**Issue by seriema** [jrcryer/generator-mean#18]
I installed the generator, scaffolded an app, and ran `grunt`. This came out:

```
$ grunt
Running "jshint:all" (jshint) task
>> 8 files lint free.

Running "compass:dist" (compass) task
   create public/styles/app.css (3.502s)
Compilation took 3.503s

Running "compass:server" (compass) task
unchanged app/styles/app.scss
Compilation took 0.112s

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Waiting...
Running "nodemon:dev" (nodemon) task
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
static-icon deprecated; switch to module serve-favicon
Express app started on port 3000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/john-philipjohansson/Documents/GitHub/whatthee/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:546:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/Users/john-philipjohansson/Documents/GitHub/whatthee/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/Users/john-philipjohansson/Documents/GitHub/whatthee/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by sdsanders** [comment]
Are you running mongodb? You need to have it running in another terminal window before running grunt.

**Comment by seriema** [comment]
Right, I noticed that :) Would be nice with some other message though hehe
